class Letra {
  int numero;
  String title;
  String letra;

  Letra({required this.numero, required this.title, required this.letra});
}

List<Letra> cantosList = [
  Letra(numero: 1, title: '1.- A CADA ', letra: '''
SEÑOR, YO QUIERO CONSTRUIR
UNA HABITACIÓN Y VIVIR JUNTO A TI.
SEÑOR, YO QUIERO CONSTRUIR
UNA HABITACIÓN Y VIVIR JUNTO A TI. 

SEÑOR, EN SUPREMA ADORACIÓN
AQUÍ ESTÁ MI CORAZÓN, QUE TE QUIERE ADORAR.
SEÑOR, EN SUPREMA ADORACIÓN

AQUÍ ESTÁ MI CORAZÓN, QUE TE QUIERE ADORAR.
A CADA INSTANTE DE MI VIDA
YO TE AGRADECERÉ
A CADA INSTANTE DE MI VIDA
YO TE AMARÉ
A CADA INSTANTE DE MI VIDA
SIEMPRE TE EXALTARE, SEÑOR.
'''),
  Letra(numero: 2, title: '2.- A LOS ', letra: '''
A LOS QUE ME TEMEIS,
SALDRA EL SOL DE JUSTICIA
Y EN SUS ALAS EL
TRAERA LA SANTIDAD.

// CON GOZO SALTAREIS EN LOS PRADOS CON MI SALVACION,
A LOS MALOS VENCEREIS
ASI HA DICHO DIOS //
'''),
  Letra(numero: 3, title: '3.- A TI', letra: '''
// A TI, OH JEHOVA, LEVANTARE MI ALMA //
DIOS MIO, EN TI CONFIO;
NO SEA AVERGONZADO,
NO SE ALEGREN DE MI MIS ENEMIGOS.
// EL ANGEL DE JEHOVA 
ACAMPA ALREDEDOR 
DE LOS QUE LE TEMEN
Y LOS DEFIENDE //
'''),
  Letra(numero: 4, title: '4.- SEÑOR', letra: '''
COMO LA NIEVE A LA MONTAÑA, SU VIDA ENTREGÓ;
COMO EL ROCÍO A LA NOCHE ASÍ MI VIDA YO TE DOY.

CORO:
A TÍ SEÑOR, QUE ERES LA FUENTE INAGOTABLE DE AMOR,
A TÍ, SEÑOR QUE ERES LA FUENTE DE AGUA VIVA, OH SEÑOR.

COMO EL SOL AL NUEVO DÍA LE HA DADO SU CALOR,
COMO LA FLOR NOS DIO EL COLOR, ASÍ MI VIDA YO TE DOY.

COMO LAS AGUAS DEL RÍO, BAJAN A UNIRSE CON EL MAR.
COMO LA NOCHE CON EL DÍA, UNIDO A TÍ, QUISIERA ESTAR
'''),
  Letra(numero: 5, title: '5.- ORAMOS', letra: '''
A VECES ORAMOS PIDIENDO
QUE DIOS NOS CONCEDA CUALQUIER NECEDAD,
A VECES PEDIMOS, PEDIMOS Y SIN DETENERNOS PARA MEDITAR.
A VECES NOS MANDA DE MAS 
NOS DA MANOS LLENAS DE PAN
Y SIN MERECERLO MI DIOS SIEMPRE ALLÍ ESTARÁ.

CORO:
GRACIAS TE DOY POR LA VIDA QUE TENGO
GRACIAS TE DOY POR QUE SIN MERECERLO
ME HAS DADO VIDA ETERNA POR SOLO CREER EN TI.

PASAMOS POR ALTO LAS COSAS
QUE DIOS NOS CONCEDE AUN SIN PEDIR
SON ESTAS LAS COSAS TAN BELLAS
QUE AL ESCUCHARLAS ME HACEN FELIZ
EL CANTO DE UN AVE AL VOLAR
LA RISA DE UN NIÑO AL JUGAR
LA PAZ QUE YO SIENTO AL SABER QUE CONMIGO ÉL ESTA.

GRACIAS TE DOY POR LA VIDA QUE TENGO
GRACIAS TE DOY POR QUE SIN MERECERLO
ME HAS DADO VIDA ETERNA POR SOLO CREER EN TI.

POR ESO GRACIAS TE DOY POR TU MISERICORDIA
GRACIAS TE DOY SEÑOR
POR QUE HAS CAMBIADO TODA MI VIDA POR TU AMOR.

'''),
];
